/*
 * Program: warmup.cpp
 * --------------------
 * Program used to generate a hash code based on user's name.
 * As given, this code has two compiler errors you need to track down
 * and fix in order to get the program up and running.
 *
 * jzelenski Thu Apr  1 12:27:53 PST 2004
 */

#include <iostream>
#include"console.h"
#include"simpio.h"
#include"main.h"
using namespace  std;

#define MAX_HASH_CODE	10000	// Upper bound for hash codes generated by program

/* Function prototypes */

int Hash(string s, int maxCode);


/*
 * Function: Hash
 * Usage: hash_number = Hash(key, max_hash);
 * -----------------------------------------
 * This function takes the key and uses it to derive a hash code,
 * which is an integer in the range [0, maxCode - 1].  The hash
 * code is computed using a method called linear congruence.
 */
#define Multiplier -1664117991L		// Multiplier used in Hash function

int Hash(string s, int maxCode)
{
    unsigned long hashcode = 0;
    for (int i = 0; i < s.length(); i++)
        hashcode = hashcode * Multiplier + s[i];
   return (hashcode % maxCode);
}

void warmup(){
    cout << "Please enter your name: ";
    string name = getLine();
    int hashcode = Hash(name,MAX_HASH_CODE);
    cout << "The hash code for your name is " << hashcode << "." <<endl;
}

int main ()
{


    cout<<"Input which you want:"<<endl;
    cout<<"[0].warm up"<<endl;
    cout<<"[1].simulate voter"<<endl;
    cout<<"[2].Chaos Games"<<endl;
    cout<<"[3].Soundex"<<endl;
    cout<<"[4].File processing and vectors"<<endl;
    cout<<"[5].plot sqrt"<<endl;
    cout<<"type:";
    int option=getInteger();

    switch (option) {
        case 0:
            warmup();
            break;
         case 1:
            simulate(500);
            break;
         case 2:
            Ghaos_Game();
            break;
         case 3:
            part3();
            break;
         case 4:
           part4();
           break;
         case 5:
            plot();
            break;
    }
    return 0;
}
