// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Phone.proto

package com.qijia.hbase;

public final class Phone {
  private Phone() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PhoneDetailOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string phonenum2 = 1;
    /**
     * <code>required string phonenum2 = 1;</code>
     *
     * <pre>
     * ID 
     * </pre>
     */
    boolean hasPhonenum2();
    /**
     * <code>required string phonenum2 = 1;</code>
     *
     * <pre>
     * ID 
     * </pre>
     */
    String getPhonenum2();
    /**
     * <code>required string phonenum2 = 1;</code>
     *
     * <pre>
     * ID 
     * </pre>
     */
    com.google.protobuf.ByteString
        getPhonenum2Bytes();

    // required string type = 2;
    /**
     * <code>required string type = 2;</code>
     *
     * <pre>
     * str 
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required string type = 2;</code>
     *
     * <pre>
     * str 
     * </pre>
     */
    String getType();
    /**
     * <code>required string type = 2;</code>
     *
     * <pre>
     * str 
     * </pre>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    // required string duration = 3;
    /**
     * <code>required string duration = 3;</code>
     *
     * <pre>
     * str 
     * </pre>
     */
    boolean hasDuration();
    /**
     * <code>required string duration = 3;</code>
     *
     * <pre>
     * str 
     * </pre>
     */
    String getDuration();
    /**
     * <code>required string duration = 3;</code>
     *
     * <pre>
     * str 
     * </pre>
     */
    com.google.protobuf.ByteString
        getDurationBytes();

    // required string time = 4;
    /**
     * <code>required string time = 4;</code>
     *
     * <pre>
     * str 
     * </pre>
     */
    boolean hasTime();
    /**
     * <code>required string time = 4;</code>
     *
     * <pre>
     * str 
     * </pre>
     */
    String getTime();
    /**
     * <code>required string time = 4;</code>
     *
     * <pre>
     * str 
     * </pre>
     */
    com.google.protobuf.ByteString
        getTimeBytes();
  }
  /**
   * Protobuf type {@code com.qijia.hbase.PhoneDetail}
   */
  public static final class PhoneDetail extends
      com.google.protobuf.GeneratedMessage
      implements PhoneDetailOrBuilder {
    // Use PhoneDetail.newBuilder() to construct.
    private PhoneDetail(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PhoneDetail(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PhoneDetail defaultInstance;
    public static PhoneDetail getDefaultInstance() {
      return defaultInstance;
    }

    public PhoneDetail getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PhoneDetail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              phonenum2_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              type_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              duration_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              time_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Phone.internal_static_com_qijia_hbase_PhoneDetail_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Phone.internal_static_com_qijia_hbase_PhoneDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PhoneDetail.class, Builder.class);
    }

    public static com.google.protobuf.Parser<PhoneDetail> PARSER =
        new com.google.protobuf.AbstractParser<PhoneDetail>() {
      public PhoneDetail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PhoneDetail(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<PhoneDetail> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string phonenum2 = 1;
    public static final int PHONENUM2_FIELD_NUMBER = 1;
    private Object phonenum2_;
    /**
     * <code>required string phonenum2 = 1;</code>
     *
     * <pre>
     * ID 
     * </pre>
     */
    public boolean hasPhonenum2() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string phonenum2 = 1;</code>
     *
     * <pre>
     * ID 
     * </pre>
     */
    public String getPhonenum2() {
      Object ref = phonenum2_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          phonenum2_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string phonenum2 = 1;</code>
     *
     * <pre>
     * ID 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPhonenum2Bytes() {
      Object ref = phonenum2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        phonenum2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private Object type_;
    /**
     * <code>required string type = 2;</code>
     *
     * <pre>
     * str 
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string type = 2;</code>
     *
     * <pre>
     * str 
     * </pre>
     */
    public String getType() {
      Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 2;</code>
     *
     * <pre>
     * str 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string duration = 3;
    public static final int DURATION_FIELD_NUMBER = 3;
    private Object duration_;
    /**
     * <code>required string duration = 3;</code>
     *
     * <pre>
     * str 
     * </pre>
     */
    public boolean hasDuration() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string duration = 3;</code>
     *
     * <pre>
     * str 
     * </pre>
     */
    public String getDuration() {
      Object ref = duration_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          duration_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string duration = 3;</code>
     *
     * <pre>
     * str 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDurationBytes() {
      Object ref = duration_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        duration_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string time = 4;
    public static final int TIME_FIELD_NUMBER = 4;
    private Object time_;
    /**
     * <code>required string time = 4;</code>
     *
     * <pre>
     * str 
     * </pre>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string time = 4;</code>
     *
     * <pre>
     * str 
     * </pre>
     */
    public String getTime() {
      Object ref = time_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          time_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string time = 4;</code>
     *
     * <pre>
     * str 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      Object ref = time_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      phonenum2_ = "";
      type_ = "";
      duration_ = "";
      time_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPhonenum2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDuration()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPhonenum2Bytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDurationBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTimeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPhonenum2Bytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDurationBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTimeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static PhoneDetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PhoneDetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PhoneDetail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PhoneDetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PhoneDetail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PhoneDetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static PhoneDetail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static PhoneDetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static PhoneDetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PhoneDetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(PhoneDetail prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.qijia.hbase.PhoneDetail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements PhoneDetailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Phone.internal_static_com_qijia_hbase_PhoneDetail_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Phone.internal_static_com_qijia_hbase_PhoneDetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PhoneDetail.class, Builder.class);
      }

      // Construct using com.qijia.hbase.Phone.PhoneDetail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        phonenum2_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        duration_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        time_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Phone.internal_static_com_qijia_hbase_PhoneDetail_descriptor;
      }

      public PhoneDetail getDefaultInstanceForType() {
        return PhoneDetail.getDefaultInstance();
      }

      public PhoneDetail build() {
        PhoneDetail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PhoneDetail buildPartial() {
        PhoneDetail result = new PhoneDetail(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.phonenum2_ = phonenum2_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.duration_ = duration_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.time_ = time_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PhoneDetail) {
          return mergeFrom((PhoneDetail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PhoneDetail other) {
        if (other == PhoneDetail.getDefaultInstance()) return this;
        if (other.hasPhonenum2()) {
          bitField0_ |= 0x00000001;
          phonenum2_ = other.phonenum2_;
          onChanged();
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000002;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasDuration()) {
          bitField0_ |= 0x00000004;
          duration_ = other.duration_;
          onChanged();
        }
        if (other.hasTime()) {
          bitField0_ |= 0x00000008;
          time_ = other.time_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPhonenum2()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasDuration()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PhoneDetail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PhoneDetail) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string phonenum2 = 1;
      private Object phonenum2_ = "";
      /**
       * <code>required string phonenum2 = 1;</code>
       *
       * <pre>
       * ID 
       * </pre>
       */
      public boolean hasPhonenum2() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string phonenum2 = 1;</code>
       *
       * <pre>
       * ID 
       * </pre>
       */
      public String getPhonenum2() {
        Object ref = phonenum2_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          phonenum2_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string phonenum2 = 1;</code>
       *
       * <pre>
       * ID 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPhonenum2Bytes() {
        Object ref = phonenum2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          phonenum2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string phonenum2 = 1;</code>
       *
       * <pre>
       * ID 
       * </pre>
       */
      public Builder setPhonenum2(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        phonenum2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string phonenum2 = 1;</code>
       *
       * <pre>
       * ID 
       * </pre>
       */
      public Builder clearPhonenum2() {
        bitField0_ = (bitField0_ & ~0x00000001);
        phonenum2_ = getDefaultInstance().getPhonenum2();
        onChanged();
        return this;
      }
      /**
       * <code>required string phonenum2 = 1;</code>
       *
       * <pre>
       * ID 
       * </pre>
       */
      public Builder setPhonenum2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        phonenum2_ = value;
        onChanged();
        return this;
      }

      // required string type = 2;
      private Object type_ = "";
      /**
       * <code>required string type = 2;</code>
       *
       * <pre>
       * str 
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string type = 2;</code>
       *
       * <pre>
       * str 
       * </pre>
       */
      public String getType() {
        Object ref = type_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string type = 2;</code>
       *
       * <pre>
       * str 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 2;</code>
       *
       * <pre>
       * str 
       * </pre>
       */
      public Builder setType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 2;</code>
       *
       * <pre>
       * str 
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 2;</code>
       *
       * <pre>
       * str 
       * </pre>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }

      // required string duration = 3;
      private Object duration_ = "";
      /**
       * <code>required string duration = 3;</code>
       *
       * <pre>
       * str 
       * </pre>
       */
      public boolean hasDuration() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string duration = 3;</code>
       *
       * <pre>
       * str 
       * </pre>
       */
      public String getDuration() {
        Object ref = duration_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          duration_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string duration = 3;</code>
       *
       * <pre>
       * str 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDurationBytes() {
        Object ref = duration_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          duration_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string duration = 3;</code>
       *
       * <pre>
       * str 
       * </pre>
       */
      public Builder setDuration(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        duration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string duration = 3;</code>
       *
       * <pre>
       * str 
       * </pre>
       */
      public Builder clearDuration() {
        bitField0_ = (bitField0_ & ~0x00000004);
        duration_ = getDefaultInstance().getDuration();
        onChanged();
        return this;
      }
      /**
       * <code>required string duration = 3;</code>
       *
       * <pre>
       * str 
       * </pre>
       */
      public Builder setDurationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        duration_ = value;
        onChanged();
        return this;
      }

      // required string time = 4;
      private Object time_ = "";
      /**
       * <code>required string time = 4;</code>
       *
       * <pre>
       * str 
       * </pre>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string time = 4;</code>
       *
       * <pre>
       * str 
       * </pre>
       */
      public String getTime() {
        Object ref = time_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string time = 4;</code>
       *
       * <pre>
       * str 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string time = 4;</code>
       *
       * <pre>
       * str 
       * </pre>
       */
      public Builder setTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string time = 4;</code>
       *
       * <pre>
       * str 
       * </pre>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <code>required string time = 4;</code>
       *
       * <pre>
       * str 
       * </pre>
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        time_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.qijia.hbase.PhoneDetail)
    }

    static {
      defaultInstance = new PhoneDetail(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.qijia.hbase.PhoneDetail)
  }

  public interface PhoneDatailDayOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .com.qijia.hbase.PhoneDetail days = 1;
    /**
     * <code>repeated .com.qijia.hbase.PhoneDetail days = 1;</code>
     */
    java.util.List<PhoneDetail>
        getDaysList();
    /**
     * <code>repeated .com.qijia.hbase.PhoneDetail days = 1;</code>
     */
    PhoneDetail getDays(int index);
    /**
     * <code>repeated .com.qijia.hbase.PhoneDetail days = 1;</code>
     */
    int getDaysCount();
    /**
     * <code>repeated .com.qijia.hbase.PhoneDetail days = 1;</code>
     */
    java.util.List<? extends PhoneDetailOrBuilder>
        getDaysOrBuilderList();
    /**
     * <code>repeated .com.qijia.hbase.PhoneDetail days = 1;</code>
     */
    PhoneDetailOrBuilder getDaysOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code com.qijia.hbase.PhoneDatailDay}
   */
  public static final class PhoneDatailDay extends
      com.google.protobuf.GeneratedMessage
      implements PhoneDatailDayOrBuilder {
    // Use PhoneDatailDay.newBuilder() to construct.
    private PhoneDatailDay(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PhoneDatailDay(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PhoneDatailDay defaultInstance;
    public static PhoneDatailDay getDefaultInstance() {
      return defaultInstance;
    }

    public PhoneDatailDay getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PhoneDatailDay(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                days_ = new java.util.ArrayList<PhoneDetail>();
                mutable_bitField0_ |= 0x00000001;
              }
              days_.add(input.readMessage(PhoneDetail.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          days_ = java.util.Collections.unmodifiableList(days_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Phone.internal_static_com_qijia_hbase_PhoneDatailDay_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Phone.internal_static_com_qijia_hbase_PhoneDatailDay_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PhoneDatailDay.class, Builder.class);
    }

    public static com.google.protobuf.Parser<PhoneDatailDay> PARSER =
        new com.google.protobuf.AbstractParser<PhoneDatailDay>() {
      public PhoneDatailDay parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PhoneDatailDay(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<PhoneDatailDay> getParserForType() {
      return PARSER;
    }

    // repeated .com.qijia.hbase.PhoneDetail days = 1;
    public static final int DAYS_FIELD_NUMBER = 1;
    private java.util.List<PhoneDetail> days_;
    /**
     * <code>repeated .com.qijia.hbase.PhoneDetail days = 1;</code>
     */
    public java.util.List<PhoneDetail> getDaysList() {
      return days_;
    }
    /**
     * <code>repeated .com.qijia.hbase.PhoneDetail days = 1;</code>
     */
    public java.util.List<? extends PhoneDetailOrBuilder>
        getDaysOrBuilderList() {
      return days_;
    }
    /**
     * <code>repeated .com.qijia.hbase.PhoneDetail days = 1;</code>
     */
    public int getDaysCount() {
      return days_.size();
    }
    /**
     * <code>repeated .com.qijia.hbase.PhoneDetail days = 1;</code>
     */
    public PhoneDetail getDays(int index) {
      return days_.get(index);
    }
    /**
     * <code>repeated .com.qijia.hbase.PhoneDetail days = 1;</code>
     */
    public PhoneDetailOrBuilder getDaysOrBuilder(
        int index) {
      return days_.get(index);
    }

    private void initFields() {
      days_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getDaysCount(); i++) {
        if (!getDays(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < days_.size(); i++) {
        output.writeMessage(1, days_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < days_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, days_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static PhoneDatailDay parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PhoneDatailDay parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PhoneDatailDay parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PhoneDatailDay parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PhoneDatailDay parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PhoneDatailDay parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static PhoneDatailDay parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static PhoneDatailDay parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static PhoneDatailDay parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PhoneDatailDay parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(PhoneDatailDay prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.qijia.hbase.PhoneDatailDay}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements PhoneDatailDayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Phone.internal_static_com_qijia_hbase_PhoneDatailDay_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Phone.internal_static_com_qijia_hbase_PhoneDatailDay_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PhoneDatailDay.class, Builder.class);
      }

      // Construct using com.qijia.hbase.Phone.PhoneDatailDay.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDaysFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (daysBuilder_ == null) {
          days_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          daysBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Phone.internal_static_com_qijia_hbase_PhoneDatailDay_descriptor;
      }

      public PhoneDatailDay getDefaultInstanceForType() {
        return PhoneDatailDay.getDefaultInstance();
      }

      public PhoneDatailDay build() {
        PhoneDatailDay result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PhoneDatailDay buildPartial() {
        PhoneDatailDay result = new PhoneDatailDay(this);
        int from_bitField0_ = bitField0_;
        if (daysBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            days_ = java.util.Collections.unmodifiableList(days_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.days_ = days_;
        } else {
          result.days_ = daysBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PhoneDatailDay) {
          return mergeFrom((PhoneDatailDay)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PhoneDatailDay other) {
        if (other == PhoneDatailDay.getDefaultInstance()) return this;
        if (daysBuilder_ == null) {
          if (!other.days_.isEmpty()) {
            if (days_.isEmpty()) {
              days_ = other.days_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDaysIsMutable();
              days_.addAll(other.days_);
            }
            onChanged();
          }
        } else {
          if (!other.days_.isEmpty()) {
            if (daysBuilder_.isEmpty()) {
              daysBuilder_.dispose();
              daysBuilder_ = null;
              days_ = other.days_;
              bitField0_ = (bitField0_ & ~0x00000001);
              daysBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDaysFieldBuilder() : null;
            } else {
              daysBuilder_.addAllMessages(other.days_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getDaysCount(); i++) {
          if (!getDays(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PhoneDatailDay parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PhoneDatailDay) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .com.qijia.hbase.PhoneDetail days = 1;
      private java.util.List<PhoneDetail> days_ =
        java.util.Collections.emptyList();
      private void ensureDaysIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          days_ = new java.util.ArrayList<PhoneDetail>(days_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          PhoneDetail, PhoneDetail.Builder, PhoneDetailOrBuilder> daysBuilder_;

      /**
       * <code>repeated .com.qijia.hbase.PhoneDetail days = 1;</code>
       */
      public java.util.List<PhoneDetail> getDaysList() {
        if (daysBuilder_ == null) {
          return java.util.Collections.unmodifiableList(days_);
        } else {
          return daysBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.qijia.hbase.PhoneDetail days = 1;</code>
       */
      public int getDaysCount() {
        if (daysBuilder_ == null) {
          return days_.size();
        } else {
          return daysBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.qijia.hbase.PhoneDetail days = 1;</code>
       */
      public PhoneDetail getDays(int index) {
        if (daysBuilder_ == null) {
          return days_.get(index);
        } else {
          return daysBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.qijia.hbase.PhoneDetail days = 1;</code>
       */
      public Builder setDays(
          int index, PhoneDetail value) {
        if (daysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDaysIsMutable();
          days_.set(index, value);
          onChanged();
        } else {
          daysBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.qijia.hbase.PhoneDetail days = 1;</code>
       */
      public Builder setDays(
          int index, PhoneDetail.Builder builderForValue) {
        if (daysBuilder_ == null) {
          ensureDaysIsMutable();
          days_.set(index, builderForValue.build());
          onChanged();
        } else {
          daysBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.qijia.hbase.PhoneDetail days = 1;</code>
       */
      public Builder addDays(PhoneDetail value) {
        if (daysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDaysIsMutable();
          days_.add(value);
          onChanged();
        } else {
          daysBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.qijia.hbase.PhoneDetail days = 1;</code>
       */
      public Builder addDays(
          int index, PhoneDetail value) {
        if (daysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDaysIsMutable();
          days_.add(index, value);
          onChanged();
        } else {
          daysBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.qijia.hbase.PhoneDetail days = 1;</code>
       */
      public Builder addDays(
          PhoneDetail.Builder builderForValue) {
        if (daysBuilder_ == null) {
          ensureDaysIsMutable();
          days_.add(builderForValue.build());
          onChanged();
        } else {
          daysBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.qijia.hbase.PhoneDetail days = 1;</code>
       */
      public Builder addDays(
          int index, PhoneDetail.Builder builderForValue) {
        if (daysBuilder_ == null) {
          ensureDaysIsMutable();
          days_.add(index, builderForValue.build());
          onChanged();
        } else {
          daysBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.qijia.hbase.PhoneDetail days = 1;</code>
       */
      public Builder addAllDays(
          Iterable<? extends PhoneDetail> values) {
        if (daysBuilder_ == null) {
          ensureDaysIsMutable();
          super.addAll(values, days_);
          onChanged();
        } else {
          daysBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.qijia.hbase.PhoneDetail days = 1;</code>
       */
      public Builder clearDays() {
        if (daysBuilder_ == null) {
          days_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          daysBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.qijia.hbase.PhoneDetail days = 1;</code>
       */
      public Builder removeDays(int index) {
        if (daysBuilder_ == null) {
          ensureDaysIsMutable();
          days_.remove(index);
          onChanged();
        } else {
          daysBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.qijia.hbase.PhoneDetail days = 1;</code>
       */
      public PhoneDetail.Builder getDaysBuilder(
          int index) {
        return getDaysFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.qijia.hbase.PhoneDetail days = 1;</code>
       */
      public PhoneDetailOrBuilder getDaysOrBuilder(
          int index) {
        if (daysBuilder_ == null) {
          return days_.get(index);  } else {
          return daysBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.qijia.hbase.PhoneDetail days = 1;</code>
       */
      public java.util.List<? extends PhoneDetailOrBuilder>
           getDaysOrBuilderList() {
        if (daysBuilder_ != null) {
          return daysBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(days_);
        }
      }
      /**
       * <code>repeated .com.qijia.hbase.PhoneDetail days = 1;</code>
       */
      public PhoneDetail.Builder addDaysBuilder() {
        return getDaysFieldBuilder().addBuilder(
            PhoneDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .com.qijia.hbase.PhoneDetail days = 1;</code>
       */
      public PhoneDetail.Builder addDaysBuilder(
          int index) {
        return getDaysFieldBuilder().addBuilder(
            index, PhoneDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .com.qijia.hbase.PhoneDetail days = 1;</code>
       */
      public java.util.List<PhoneDetail.Builder>
           getDaysBuilderList() {
        return getDaysFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          PhoneDetail, PhoneDetail.Builder, PhoneDetailOrBuilder>
          getDaysFieldBuilder() {
        if (daysBuilder_ == null) {
          daysBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              PhoneDetail, PhoneDetail.Builder, PhoneDetailOrBuilder>(
                  days_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          days_ = null;
        }
        return daysBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.qijia.hbase.PhoneDatailDay)
    }

    static {
      defaultInstance = new PhoneDatailDay(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.qijia.hbase.PhoneDatailDay)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qijia_hbase_PhoneDetail_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_qijia_hbase_PhoneDetail_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_qijia_hbase_PhoneDatailDay_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_qijia_hbase_PhoneDatailDay_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013Phone.proto\022\017com.qijia.hbase\"N\n\013PhoneD" +
      "etail\022\021\n\tphonenum2\030\001 \002(\t\022\014\n\004type\030\002 \002(\t\022\020" +
      "\n\010duration\030\003 \002(\t\022\014\n\004time\030\004 \002(\t\"<\n\016PhoneD" +
      "atailDay\022*\n\004days\030\001 \003(\0132\034.com.qijia.hbase" +
      ".PhoneDetail"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_qijia_hbase_PhoneDetail_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_qijia_hbase_PhoneDetail_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_qijia_hbase_PhoneDetail_descriptor,
              new String[] { "Phonenum2", "Type", "Duration", "Time", });
          internal_static_com_qijia_hbase_PhoneDatailDay_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_qijia_hbase_PhoneDatailDay_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_qijia_hbase_PhoneDatailDay_descriptor,
              new String[] { "Days", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
