version: '3'
services: 
    mdb:
        image: mongo
        ports:
            - 27017:27017
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=mathai
            - MONGO_INITDB_ROOT_PASSWORD=mathai
    mdbui:
        image: mongo-express
        ports:
            - 8081:8081
        environment: 
            - ME_CONFIG_MONGODB_SERVER=mdb
            - ME_CONFIG_MONGODB_ADMINUSERNAME=mathai
            - ME_CONFIG_MONGODB_ADMINPASSWORD=mathai
